CREATE TABLE teachers (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	is_active BOOLEAN DEFAULT TRUE,
	start_date DATE,
	end_date DATE
);

CREATE TABLE assistance_requests (
	id SERIAL PRIMARY KEY NOT NULL,
	student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  	teacher_id SERIAL REFERENCES teachers(id) ON DELETE CASCADE,
	assignment_id SERIAL REFERENCES assignments(id) ON DELETE CASCADE,
	CREATED_AT TIMESTAMP,
	STARTED_AT TIMESTAMP,
	COMPLETED_AT TIMESTAMP,
	STUDENT_FEEDBACK TEXT,
	TEACHER_FEEDBACK TEXT
);
